
module.exports.ErrorMessage = Object.freeze({
  INVALID_TOKEN: 'Unauthorized user.',
  COUNTRY_EXIST: 'Country name already exist',
  INTERNAL_ERROR: 'Internal Server Error.',
  INVALID_CREDENTIAL: 'Invalid credentials.',
  SOMETHING_WRONG: 'Something went wrong!',
  ALREADY_EXIST: 'Already exists.',
  NO_TOKEN: 'Please provide token.',
  EMAIL_NOT_REGISTERED: 'Provided email is not registered.',
  NOT_REGISTERED: "Provided mobileNumber is not registered.",
  RESET_PASSWORD_EXPIRED: 'Your Token has expired.',
  WRONG_PASSWORD: 'Please enter valid password.',
  INVALID_MOBILE: 'This mobile number is not valid.',
  EMAIL_EXIST: 'This email already exists.',
  NOT_FOUND: 'Requested data not found.',
  USER_NOT_FOUND: 'This user does not exist.',
  UPDATE_NOT: "Unexpected error during update, please try again.",
  MOBILE_EXIST: 'This mobile number already exists.',
  PARTICIPANT_EXIST: "This participant ID already exists.",
  USERNAME_EXIST: 'This user name already exists.',
  USER_ID: 'A valid User Id is required.',
  BLOCKED_BY_ADMIN: 'You are not authorized, please contact Admin.',
  DELETED_BY_ADMIN: 'Your account is deleted, please contact Admin.',
  FIELD_REQUIRED: 'Fields are required.',
  OLD_PASSWORD: 'You have provided an incorrect old password.',
  INCORRECT_JWT: 'Invalid JWT token.',
  FORBIDDEN: 'There was an error in sending email.',
  INVALID_OTP: 'Invalid OTP',
  OTP_EXPIRED: "OTP has expired, please try resend OTP.",
  PASSMATCH: "Password do not match.",
  NOT_MATCH: "Password not matched.",
  INSUFFICIENT_BALANCE: "Insufficient balance in your account.",
  SLOT_BOOk: " This slot already booked",
  RIDE_BOOK: " This ride already booked",
  UPLOAD_DOCUMENT: "Your otp has been verified, Please verified your document.",
  ADD_MONEY: "Please first add money in your wallet.",
  ALREADY_WITHDRAW_REQUEST: "You already request for withdraw, you request in process.",
  PAYMENT_ALREADY_DONE: "Payment already done.",
  MOMEY_INSUFFICENT: "In your wallet insufficent fund.",
})
module.exports.SuccessMessage = Object.freeze({
  SIGNUP_SUCCESSFULLY: "Thanks, You have successfully signed up.",
  LOGIN_SUCCESS: 'Login Successfully!',
  LOGOUT_SUCCESS: 'Your account has been logout successfully.',
  USER_CREATE: "User has been created successfully.",
  CUSTOMER_VERIFY: 'Customer verified successfully',
  CUSTOMER_ALREADY_VERIFY: 'Otp already verified.',
  FORGET_SUCCESS: 'A password link has been sent to your registered email ID.',
  RESET_SUCCESS: 'Your password has been successfully changed.',
  PRODUCT_LIST_FETCH: 'Successfully fetched product list.',
  UPLOAD_DOCUMENT: "Your document has been upload successfully.",
  DOCUMENT_ALREADY_UPLOAD: "Document already upload.",
  DOCUMENT_NOT_VERIFIED: "Document not verified.",
  USER_LIST_FETCH: 'Successfully fetched user list.',
  AUTHORIZATION: 'This User is Authorized.',
  ACCOUNT_CREATION: 'Your account has been created successfully.',
  EMAIL_SEND: "OTP has been sent to your registered Email successfully.",
  OTP_SEND: 'OTP sent successfully.',
  VERIFY_OTP: 'OTP verified successfully.',
  PIN_SET: "Your Pin has been set successfully.",
  PASSWORD_UPDATE: "Your password has been updated successfully.",
  DATA_SAVED: "Data is saved successfully.",
  DETAIL_GET: "Details have been fetched successfully.",
  DATA_FOUND: "Requested data found",
  PROFILE_DETAILS: "Your profile details has been updated sucessfully.",
  STATUS_UPDATED: "Your Status has been changed successfully.",
  UPDATE_SUCCESS: "Successfully updated.",
  BLOCK_SUCCESS: "Successfully blocked.",
  UNBLOCK_SUCCESS: "Successfully activated.",
  DELETE_SUCCESS: "Successfully deleted.",
  SMS_SEND: "The SMS has been send to the buddies successfully.",
  CATEGORY_ADD: "Category has been added successfully.",
  MESSAGE_ADD: "The message has been added successfully.",
  PRODUCT_ADD: "Product has been added successfully.",
  TRANSACTION_DONE: "Transaction done successfully.",
  KYC_REJECT: "Kyc is rejeted successfully.",
  KYC_ACCEPT: "Kyc is accepted successfully.",
  REJECT_BOOKING: "Cancel booking successfully.",
  FAVOURITE_SUCCESS: "Item has been favourited successfully.",
  UNFAVOURITE_SUCCESS: "Item has been unfavourited successfully.",
  INCREMENTED: "Successfully incremented by value 1.",
  DECREMENTED: "Successfully decremented by value 1.",
  CART_SAVED: "Added successfully.",
  CART_ALREADY: " Already exist.",
  BROADCAST_SUCCESS: "Send Broadcast Message Sucessfully",
  LOCATION_UPDATE_SUCCESS: "Location update Successfully.",
  ONLINE_UPDATE_SUCCESS: "User online status update Successfully.",
})
